# Generated by Django 5.2.17 on 2026-09-21 13:55

import apps.quiz.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.quiz.models.generate_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'Devam ediyor'), ('completed', 'Tamamlandı'), ('abandoned', 'Terk edildi')], db_index=True, default='in_progress', max_length=16)),
                ('total_questions', models.PositiveSmallIntegerField(default=20)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('timeout_count', models.PositiveSmallIntegerField(default=0)),
                ('client_platform', models.CharField(blank=True, choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('client_version', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.category')),
            ],
            options={
                'verbose_name': 'quiz oturumu',
                'verbose_name_plural': 'quiz oturumları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('pending', 'Bekliyor'), ('correct', 'Doğru'), ('wrong', 'Yanlış'), ('timeout', 'Süre doldu')], default='pending', max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.answeroption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quizsession')),
            ],
            options={
                'verbose_name': 'oturum sorusu',
                'verbose_name_plural': 'oturum soruları',
                'ordering': ['session', 'order'],
                'constraints': [models.UniqueConstraint(fields=('session', 'order'), name='uniq_session_order'), models.UniqueConstraint(fields=('session', 'question'), name='uniq_session_question')],
            },
        ),
    ]
