# Generated by Django 5.2.17 on 2026-09-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=20)),
                ('score', models.PositiveIntegerField(db_index=True)),
                ('correct_count', models.PositiveSmallIntegerField()),
                ('total_elapsed_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.category')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='quiz.quizsession')),
            ],
            options={
                'verbose_name': 'skor kaydı',
                'verbose_name_plural': 'skor kayıtları',
                'ordering': ['-score', 'total_elapsed_ms', 'created_at', 'id'],
                'indexes': [models.Index(models.F('category'), models.OrderBy(models.F('score'), descending=True), models.F('total_elapsed_ms'), name='lb_category_rank_idx'), models.Index(models.OrderBy(models.F('score'), descending=True), models.F('total_elapsed_ms'), name='lb_overall_rank_idx')],
            },
        ),
    ]
