# Generated by Django 5.2.17 on 2026-09-21 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('color_hex', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Renk #RRGGBB formatında olmalı.')])),
                ('icon', models.CharField(max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategoriler',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(300)])),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('times_served', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.category')),
            ],
            options={
                'verbose_name': 'soru',
                'verbose_name_plural': 'sorular',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.question')),
            ],
            options={
                'verbose_name': 'şık',
                'verbose_name_plural': 'şıklar',
                'ordering': ['question', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'is_active'], name='question_cat_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'display_order'), name='uniq_option_order_per_question'),
        ),
    ]
